name: kazoo-application-cdr
custom_files: null
exposure: private
base_branch: origin/master
base_core: kazoo
template: kazoo-application.spec.tmpl
package:
  centos7:
    name: kazoo-application-cdr
    summary: 'Kazoo core application'
    description: |
      Responsible for receving CDR events off the AMQP bus and inserting the CDR
      into the database (after some data munging).
    app_name: cdr
    license: 'MPL 2.0'
    group: Productivity/Telephony
    url: 'https://2600hz.org/'
    vendor: 2600Hz
  rockylinux8:
    name: kazoo-application-cdr
    summary: 'Kazoo core application'
    description: |
      Responsible for receving CDR events off the AMQP bus and inserting the CDR
      into the database (after some data munging).
    app_name: cdr
    license: 'MPL 2.0'
    group: Productivity/Telephony
    url: 'https://2600hz.org/'
    vendor: 2600Hz
    dist: .el8
  rockylinux9:
    name: kazoo-application-cdr
    summary: 'Kazoo core application'
    description: |
      Responsible for receving CDR events off the AMQP bus and inserting the CDR
      into the database (after some data munging).
    app_name: cdr
    license: 'MPL 2.0'
    group: Productivity/Telephony
    url: 'https://2600hz.org/'
    vendor: 2600Hz
    dist: .el9
metapackage:
  -
    name: meta-kazoo-applications
    type: required
    branch: 'master'
    package: kazoo-application-cdr
dependencies: null
