---
name: kazoo-application-ast
base_branch: origin/master
metapackage:
  - name: meta-kazoo-applications
    type: related
    branch: 'master'
    package: kazoo-application-ast
base_core: kazoo
template: kazoo-application.spec.tmpl
package:
  centos7:
    name: kazoo-application-ast
    summary: Kazoo Abstract Syntax Tree App
    description: |
      Kazoo AST parsing for introspection
    app_name: ast
    license: MPL 2.0
    group: Productivity/Telephony
    url: https://2600hz.com/
    vendor: 2600Hz
  rockylinux8:
    name: kazoo-application-ast
    summary: 'Kazoo core application'
    description: |
      KAZOO REST API server
    app_name: ast
    license: 'MPL 2.0'
    group: Productivity/Telephony
    url: 'https://2600hz.org/'
    vendor: 2600Hz
    dist: .el8
  rockylinux9:
    name: kazoo-application-ast
    summary: 'Kazoo core application'
    description: |
      KAZOO REST API server
    app_name: ast
    license: 'MPL 2.0'
    group: Productivity/Telephony
    url: 'https://2600hz.org/'
    vendor: 2600Hz
    dist: .el9

