  - 'Crossbar - REST Interface to the stars':
    - 'applications/crossbar/doc/402.md'
    - 'applications/crossbar/doc/README.md'
    - 'applications/crossbar/doc/about.md'
    - 'applications/crossbar/doc/access_lists.md'
    - 'applications/crossbar/doc/accounts.md'
    - 'applications/crossbar/doc/acls.md'
    - 'applications/crossbar/doc/agents.md'
    - 'applications/crossbar/doc/alerts.md'
    - 'applications/crossbar/doc/allotments.md'
    - 'applications/crossbar/doc/api_authentication.md'
    - 'applications/crossbar/doc/applications.md'
    - 'applications/crossbar/doc/apps_link.md'
    - 'applications/crossbar/doc/apps_store.md'
    - 'applications/crossbar/doc/att_handlers_errors.md'
    - 'applications/crossbar/doc/auth.md'
    - 'applications/crossbar/doc/basic_auth.md'
    - 'applications/crossbar/doc/basics.md'
    - 'applications/crossbar/doc/blacklists.md'
    - 'applications/crossbar/doc/braintree.md'
    - 'applications/crossbar/doc/call_inspector.md'
    - 'applications/crossbar/doc/call_reports.md'
    - 'applications/crossbar/doc/callflows.md'
    - 'applications/crossbar/doc/cb_apps_maintenance.md'
    - 'applications/crossbar/doc/cccps.md'
    - 'applications/crossbar/doc/cdrs.md'
    - 'applications/crossbar/doc/channels.md'
    - 'applications/crossbar/doc/clicktocall.md'
    - 'applications/crossbar/doc/comments.md'
    - 'applications/crossbar/doc/commland.md'
    - 'applications/crossbar/doc/conference.md'
    - 'applications/crossbar/doc/conference_auth.md'
    - 'applications/crossbar/doc/configs.md'
    - 'applications/crossbar/doc/configuration.md'
    - 'applications/crossbar/doc/connectivity.md'
    - 'applications/crossbar/doc/contact_list.md'
    - 'applications/crossbar/doc/devices.md'
    - 'applications/crossbar/doc/dialplans.md'
    - 'applications/crossbar/doc/directories.md'
    - 'applications/crossbar/doc/endpoints.md'
    - 'applications/crossbar/doc/external_numbers.md'
    - 'applications/crossbar/doc/faxboxes.md'
    - 'applications/crossbar/doc/faxes.md'
    - 'applications/crossbar/doc/filters.md'
    - 'applications/crossbar/doc/functions.md'
    - 'applications/crossbar/doc/getstream.md'
    - 'applications/crossbar/doc/groups.md'
    - 'applications/crossbar/doc/hotdesks.md'
    - 'applications/crossbar/doc/how_to_authenticate.md'
    - 'applications/crossbar/doc/i18n.md'
    - 'applications/crossbar/doc/inbound_messaging.md'
    - 'applications/crossbar/doc/ip_auth.md'
    - 'applications/crossbar/doc/ips.md'
    - 'applications/crossbar/doc/ledgers.md'
    - 'applications/crossbar/doc/limits.md'
    - 'applications/crossbar/doc/lists.md'
    - 'applications/crossbar/doc/maintenance.md'
    - 'applications/crossbar/doc/match_lists.md'
    - 'applications/crossbar/doc/media.md'
    - 'applications/crossbar/doc/menus.md'
    - 'applications/crossbar/doc/metaflows.md'
    - 'applications/crossbar/doc/migrations.md'
    - 'applications/crossbar/doc/mms.md'
    - 'applications/crossbar/doc/multi_factor.duo.md'
    - 'applications/crossbar/doc/multi_factor.md'
    - 'applications/crossbar/doc/multipart.md'
    - 'applications/crossbar/doc/notifications.md'
    - 'applications/crossbar/doc/parked_calls.md'
    - 'applications/crossbar/doc/phone_numbers.md'
    - 'applications/crossbar/doc/pivot.md'
    - 'applications/crossbar/doc/port_requests.md'
    - 'applications/crossbar/doc/presence.md'
    - 'applications/crossbar/doc/pushes.md'
    - 'applications/crossbar/doc/queues.md'
    - 'applications/crossbar/doc/quickcall.md'
    - 'applications/crossbar/doc/quickroutes.md'
    - 'applications/crossbar/doc/rate_limiting.md'
    - 'applications/crossbar/doc/rate_limits.md'
    - 'applications/crossbar/doc/rates.md'
    - 'applications/crossbar/doc/recordings.md'
    - 'applications/crossbar/doc/registrations.md'
    - 'applications/crossbar/doc/resource_selectors.md'
    - 'applications/crossbar/doc/resource_templates.md'
    - 'applications/crossbar/doc/resources.md'
    - 'applications/crossbar/doc/reverse_proxy.md'
    - 'applications/crossbar/doc/schemas.md'
    - 'applications/crossbar/doc/scope_restrictions.md'
    - 'applications/crossbar/doc/scopes.md'
    - 'applications/crossbar/doc/screenpops.md'
    - 'applications/crossbar/doc/sdks.md'
    - 'applications/crossbar/doc/search.md'
    - 'applications/crossbar/doc/securing_crossbar.md'
    - 'applications/crossbar/doc/security.md'
    - 'applications/crossbar/doc/services.md'
    - 'applications/crossbar/doc/skels.md'
    - 'applications/crossbar/doc/sms.md'
    - 'applications/crossbar/doc/storage.http.md'
    - 'applications/crossbar/doc/storage.md'
    - 'applications/crossbar/doc/storage.s3.md'
    - 'applications/crossbar/doc/sup.md'
    - 'applications/crossbar/doc/system_configs.md'
    - 'applications/crossbar/doc/system_status.md'
    - 'applications/crossbar/doc/tasks.md'
    - 'applications/crossbar/doc/temporal_rules.md'
    - 'applications/crossbar/doc/temporal_rules_sets.md'
    - 'applications/crossbar/doc/token_auth.md'
    - 'applications/crossbar/doc/token_restrictions.md'
    - 'applications/crossbar/doc/transactions.md'
    - 'applications/crossbar/doc/user_authentication.md'
    - 'applications/crossbar/doc/users.md'
    - 'applications/crossbar/doc/voicemail.md'
    - 'applications/crossbar/doc/webhooks.md'
    - 'applications/crossbar/doc/websites.md'
    - 'applications/crossbar/doc/websockets.md'
    - 'applications/crossbar/doc/whitelabeling.md'
    - 'applications/crossbar/doc/wordle.md'
