  - 'Properly - Proper Statem and KAZOO testing':
    - 'applications/properly/doc/README.md'
    - 'applications/properly/doc/engineering.md'
    - 'applications/properly/doc/maintenance.md'
    - 'applications/properly/doc/rates.md'
