  - 'Pivot: Accept 3rd party dialplan commands to control calls':
    - 'applications/pivot/doc/README.md'
    - 'applications/pivot/doc/issues.md'
    - 'applications/pivot/doc/kazoo/README.md'
    - 'applications/pivot/doc/kazoo/bridging.md'
    - 'applications/pivot/doc/kazoo/collect.md'
    - 'applications/pivot/doc/kazoo/conferencing.md'
    - 'applications/pivot/doc/kazoo/dtmf.md'
    - 'applications/pivot/doc/kazoo/hangups.md'
    - 'applications/pivot/doc/kazoo/play.md'
    - 'applications/pivot/doc/kazoo/presence.md'
    - 'applications/pivot/doc/kazoo/recording.md'
    - 'applications/pivot/doc/kazoo/say.md'
    - 'applications/pivot/doc/requests.md'
    - 'applications/pivot/doc/twiml/README.md'
