  - 'Tasks: Schedule tasks for background running':
    - 'applications/tasks/doc/README.md'
    - 'applications/tasks/doc/cdrs.md'
    - 'applications/tasks/doc/compaction.md'
    - 'applications/tasks/doc/fax_cleanup.md'
    - 'applications/tasks/doc/kazoo_bill_early_task.md'
    - 'applications/tasks/doc/kz_notify_resender.md'
    - 'applications/tasks/doc/ledger_rollover.md'
    - 'applications/tasks/doc/maintenance.md'
    - 'applications/tasks/doc/modb_creation.md'
    - 'applications/tasks/doc/notify_resend_maintenance.md'
    - 'applications/tasks/doc/rates.md'
    - 'applications/tasks/doc/services_rollover.md'
